spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/order
    username: sa

  # Kafka
  kafka:
    # Consumer 설정
    consumer:
      # Kafka Broker 서버
      bootstrap-servers: localhost:9092
      # 해당 Consumer 소비 그룹 ID
      group-id: group-01
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    # Producer 설정
    producer:
      # Kafka Broker 서버
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 18001